### ISSUE TITLE
how-to just fold/unfold the t.o.c. so prevent it didn't flow off when on e.g. phone screens?

### ISSUE THREAD

**Issue by Txellenne** [clojure-cookbook/clojure-cookbook#443]
Hi, 
I'd appreciate any idea on the following issue: 
Question is that whenever I have to check the handbook on my telephone screen and I should zoom the page I'm reading, the t.o.c side bar got also zoomed but in a proportion that invades the rest of the screen, it's annoying. I just have to stop reading til get home. I'd love to have the otherwise useful t.o.c. get folded or unfolded when required but I've been no able to do it, any idea?. 
As said, I'd appreciate it so so much.
Txe.

**Comment by rkneufeld** [comment]
Can you let me know which platform and version of the book you're working with?

**Comment by Txellenne** [comment]
Hi, Thanks for your reply.
I go on Fedora 21 and the book version is the currently available here this site at.

**Comment by rkneufeld** [comment]
Sorry, I meant to ask: are you reading the book via this repository at the source level, generating a pdf/epub/mobi from the repository, or via an official O'Reilly version?

**Comment by Txellenne** [comment]
Ah. Ok. I got generated an html file from this repository.

**Comment by rkneufeld** [comment]
I'm not sure then what to do. It may be possible to influence the styling of the generated HTML, but I can't say I have any experience on how to make that happen.

**Comment by Txellenne** [comment]
Hey!, yep. Well, I though there was a known way of sort out my question. So, that said I started to, yeap, adjust the css style section in the html file though, basically by trial and error. Now i got it readable, bd.
I include them here just in case is of help for someone else:
```css
/* line 166 (approx). WARNING please take the line number as reference, only. 
/* It may be different in your asciidoc output.
/* giving a proportional width feature to the sidebarblock makes it to get reduced if 
/* the the screen push for it.

div.sidebarblock > div.content {
float: left;
width: 20%;
}

/* line 540 This tells the body content to make room for the sidebarblock
@media screen {
  body {
    (...)
    margin-left: 20%;
  }

/* lines 555, 556 keep the above feature synchronized at the t.o.c. div
#toc {
(...)
float: left;
width: 20%;
}

/* line 71. Once defined a new margin to sidebarblock the content section get 
/* affected with a negative margin, this line correct that. 

div.sectionbody {
  margin-left: 25px;
}
```
```html
/* lines 771 (and 779). Same issue regarding a negative margin when at 
/* Title and Preface. But the only way I found to correct it is by doing an
/* inline alignment as show below:

<h1><p align="center">Clojure Cookbook</p></h1>

/* line 779
<h2 id="_preface"><p align="center">Preface</p></h2>
```
